spring:
  application:
    name: smarttasks
  datasource:
    url: jdbc:postgresql://localhost:5432/smarttasks
    username: smart
    password: smart
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: password
  bucketName: smarttasks